### ISSUE TITLE
fabric ?

### ISSUE THREAD

**Issue by ydainna** [dscalzi/HeliosLauncher#198] opened 2021-10-27 14:46 UTC
Hello
is it possible to make the launcher compatible with fabric please?
thanks to you

**Comment by Neerfix** [comment] 2021-11-01 11:43
see : https://github.com/dscalzi/HeliosLauncher/issues/65

**Comment by MJRamon** [comment] 2022-05-02 22:56
Gonna raise this question once again, cause it's been a long time without any news on this. Very much needed.

**Comment by dscalzi** [comment] 2022-05-03 19:17
It's not planned

**Comment by MJRamon** [comment] 2022-05-03 20:02
Can I ask you to reconsider? Nowadays Fabric is represented widely, and plays a huge role in Minecraft modding world.
Your launcher is one the best out there, and it would be a great tool for all of us, who use Fabric. Please, don't leave us without this opportunity :)

**Comment by dscalzi** [comment] 2023-03-18 08:21
Once assetguard-2 (#270) lands, the next thing to rework would be processbuilder.js. That would be done with fabric support in mind.

**Comment by dscalzi** [comment] 2023-03-24 22:45
closing as duplicate of #65

**Closed as completed by dscalzi** 2023-03-24 22:45 UTC
Labels: duplicate
