### ISSUE TITLE
Crash when launching custom Modpack

### ISSUE THREAD

**Issue by HerrBeef** [dscalzi/HeliosLauncher#62] opened 2020-05-01 17:07 UTC
Hi,

i've always experiencing the same error with modpacks (for example All The Mods 5) with versions higher than 1.12.

It starts always with: 
"ava.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97) ~[forge-1.15.2-31.1.63-client.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}"

This error doesn't come when i run the same modpack in Twitch Launcher or in MultiMC. so it seems it's an error with the launcher. And i cant figure out what is causing it. It seems that some mods are not compatible with the launcher.

btw i've tried multiple forge versions. and removing some mods. and it works with removing some mods, thats why i assume that some mods don't work with this launcher.

**Comment by dscalzi** [comment] 2020-05-01 23:12
This is not helpful at all. You're probably missing libraries or setup your configuration improperly.

**Comment by HerrBeef** [comment] 2020-05-03 08:05
I've found out which mod causes it. MixinBootstrap is not working with the Launcher.
https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap

And all mods which need this mod.

I think that the mod id is not correctly generated.
"generated.forgemod:mixinbootstrap-1.0.3:0.0.0@jar"

**Comment by dscalzi** [comment] 2020-05-03 08:06
What's not working about it?

**Comment by HerrBeef** [comment] 2020-05-03 08:42
It's not loading properly.
![grafik](https://user-images.githubusercontent.com/12501633/80909697-85229380-8d2a-11ea-9d93-47985ceb268c.png)

on multimc or twitch launcher this doesnt happen.
Here the log:
[latest.log](https://github.com/dscalzi/HeliosLauncher/files/4569843/latest.log)

**Comment by dscalzi** [comment] 2020-05-03 09:22
Ok, is it a mod file or a library file. If it's a library, add it as a library.

**Comment by HerrBeef** [comment] 2020-05-03 09:38
It's an modfile. At least i think it is. Twitch Launcher has it in mods folder. MultiMC has it in mods folder.

**Comment by dscalzi** [comment] 2020-05-03 09:39
Are you sure you're running it with th exact same configuration as you have in the twitch launcher (same exact forge version, optifine vs no optifine, etc)

**Comment by HerrBeef** [comment] 2020-05-03 09:43
Yes. i copied the jar files that were in the mods folder to forgemods and the config, scripts and packmenu folder in files folder. 
And it's using Forge 31.1.63. 
Optifine is not included in this pack because it's 1.15.2 and there is no stable Optifine version.

if i remove mixinbootstrap and all mods which need this mod. The modpack starts fine.

**Comment by dscalzi** [comment] 2020-05-03 10:01
Can you zip your nebula server and send it to me

**Comment by HerrBeef** [comment] 2020-05-03 11:02
Hi, 
here is the Link to the zip file:
https://launcher.floot.host/backup/distribution.zip

here the link to the distribution.json:
https://launcher.floot.host/backup/distribution.json
where everything is hosted.

**Comment by HerrBeef** [comment] 2020-05-09 09:31
Can you reproduce the error?

**Comment by dscalzi** [comment] 2020-05-11 23:37
I haven't had a chance to set it up yet.

**Comment by dscalzi** [comment] 2020-05-18 19:42
I will look into this today

**Comment by dscalzi** [comment] 2020-05-18 21:16
@HerrBeef I was able to reproduce the issue. The problem is that mixinbootstrap does not contain a `mods.toml` file, therefore fml is not able to load it. It seems that the file would be loadable from the `mods` directory, but I would like to avoid that if possible. Ideally loading from `--fml.mods` and the `mods` directory should be identical.

I don't have time to study the internals of the mod with regard to how it loads in forge. Hoping for a quick reply from the author (https://github.com/LXGaming/MixinBootstrap/issues/10)

**Comment by dscalzi** [comment] 2020-05-19 01:40
@HerrBeef Could you try adding MixinBootstrap as a `Library` rather than ForgeMod and let me know if that works for you?

**Comment by HerrBeef** [comment] 2020-05-19 06:34
I can try. How do i add it as library? Should i Create a folder which says library? Or does this work differently

**Comment by dscalzi** [comment] 2020-05-19 06:48
It looks like I haven't added a folder for libraries on Nebula yet. For now you would have to add it manually as type `Library`.

**Comment by HerrBeef** [comment] 2020-05-19 11:24
I have added it as Library and it seems to work. No Crash no error. Updated the files there:
here is the Link to the zip file:
https://launcher.floot.host/backup/distribution.zip

here the link to the distribution.json:
https://launcher.floot.host/backup/distribution.json
where everything is hosted.

Can we somehow automate the import for this mod? or is it up to the mod creator?

**Comment by dscalzi** [comment] 2020-05-19 15:50
The automation would be to add support for Library resolution in nebula, which I will do when I get a chance. This would be something like dropping the jar into `libraries` rather than `forgemods`. Again though, I just need to find time to add it.

I'll close this issue once the feature is in. (see https://github.com/dscalzi/Nebula/issues/2)

**Comment by dscalzi** [comment] 2020-05-20 01:53
@HerrBeef Support added to Nebula as of https://github.com/dscalzi/Nebula/commit/afcae366b53c31211865ab9d7bcc5dbb8b9f2271. Simply put mixinbootstrap into the `libraries` directory.

**Closed by dscalzi** 2020-05-20 01:53 UTC
